/**
 * How to add a new license:
 * 1. Go to https://regex101.com
 * 2. Set the function to 'Substitution' and RegEx flags to 'gm'
 * 3. Copy the license text from somewhere and paste it in the 'TEST STRING' box
 * 4. Set the search expression to '"'
 * 5. Set the substitution expression to '\\"'
 * 6. Copy the output of the substition text into the 'TEST STRING' box
 * 7. Set the search expression to '(.*)\R?'
 * 8. Set the substitution expression to '"$1\\n"\n'
 * 9. Copy the output, ignore the last line ('"\n"')
 * 10. Paste it below into the correct index position
 * 11. Add a comment above it mentioning its name ('LICENSE: ...')
*/

const char *LICENSES[] = {

  // LICENSE: CC-BY-4.0
  "Attribution 4.0 International\n"
  "\n"
  "=======================================================================\n"
  "\n"
  "Creative Commons Corporation (\"Creative Commons\") is not a law firm and\n"
  "does not provide legal services or legal advice. Distribution of\n"
  "Creative Commons public licenses does not create a lawyer-client or\n"
  "other relationship. Creative Commons makes its licenses and related\n"
  "information available on an \"as-is\" basis. Creative Commons gives no\n"
  "warranties regarding its licenses, any material licensed under their\n"
  "terms and conditions, or any related information. Creative Commons\n"
  "disclaims all liability for damages resulting from their use to the\n"
  "fullest extent possible.\n"
  "\n"
  "Using Creative Commons Public Licenses\n"
  "\n"
  "Creative Commons public licenses provide a standard set of terms and\n"
  "conditions that creators and other rights holders may use to share\n"
  "original works of authorship and other material subject to copyright\n"
  "and certain other rights specified in the public license below. The\n"
  "following considerations are for informational purposes only, are not\n"
  "exhaustive, and do not form part of our licenses.\n"
  "\n"
  "     Considerations for licensors: Our public licenses are\n"
  "     intended for use by those authorized to give the public\n"
  "     permission to use material in ways otherwise restricted by\n"
  "     copyright and certain other rights. Our licenses are\n"
  "     irrevocable. Licensors should read and understand the terms\n"
  "     and conditions of the license they choose before applying it.\n"
  "     Licensors should also secure all rights necessary before\n"
  "     applying our licenses so that the public can reuse the\n"
  "     material as expected. Licensors should clearly mark any\n"
  "     material not subject to the license. This includes other CC-\n"
  "     licensed material, or material used under an exception or\n"
  "     limitation to copyright. More considerations for licensors:\n"
  "	wiki.creativecommons.org/Considerations_for_licensors\n"
  "\n"
  "     Considerations for the public: By using one of our public\n"
  "     licenses, a licensor grants the public permission to use the\n"
  "     licensed material under specified terms and conditions. If\n"
  "     the licensor's permission is not necessary for any reason--for\n"
  "     example, because of any applicable exception or limitation to\n"
  "     copyright--then that use is not regulated by the license. Our\n"
  "     licenses grant only permissions under copyright and certain\n"
  "     other rights that a licensor has authority to grant. Use of\n"
  "     the licensed material may still be restricted for other\n"
  "     reasons, including because others have copyright or other\n"
  "     rights in the material. A licensor may make special requests,\n"
  "     such as asking that all changes be marked or described.\n"
  "     Although not required by our licenses, you are encouraged to\n"
  "     respect those requests where reasonable. More_considerations\n"
  "     for the public:\n"
  "	wiki.creativecommons.org/Considerations_for_licensees\n"
  "\n"
  "=======================================================================\n"
  "\n"
  "Creative Commons Attribution 4.0 International Public License\n"
  "\n"
  "By exercising the Licensed Rights (defined below), You accept and agree\n"
  "to be bound by the terms and conditions of this Creative Commons\n"
  "Attribution 4.0 International Public License (\"Public License\"). To the\n"
  "extent this Public License may be interpreted as a contract, You are\n"
  "granted the Licensed Rights in consideration of Your acceptance of\n"
  "these terms and conditions, and the Licensor grants You such rights in\n"
  "consideration of benefits the Licensor receives from making the\n"
  "Licensed Material available under these terms and conditions.\n"
  "\n"
  "\n"
  "Section 1 -- Definitions.\n"
  "\n"
  "  a. Adapted Material means material subject to Copyright and Similar\n"
  "     Rights that is derived from or based upon the Licensed Material\n"
  "     and in which the Licensed Material is translated, altered,\n"
  "     arranged, transformed, or otherwise modified in a manner requiring\n"
  "     permission under the Copyright and Similar Rights held by the\n"
  "     Licensor. For purposes of this Public License, where the Licensed\n"
  "     Material is a musical work, performance, or sound recording,\n"
  "     Adapted Material is always produced where the Licensed Material is\n"
  "     synched in timed relation with a moving image.\n"
  "\n"
  "  b. Adapter's License means the license You apply to Your Copyright\n"
  "     and Similar Rights in Your contributions to Adapted Material in\n"
  "     accordance with the terms and conditions of this Public License.\n"
  "\n"
  "  c. Copyright and Similar Rights means copyright and/or similar rights\n"
  "     closely related to copyright including, without limitation,\n"
  "     performance, broadcast, sound recording, and Sui Generis Database\n"
  "     Rights, without regard to how the rights are labeled or\n"
  "     categorized. For purposes of this Public License, the rights\n"
  "     specified in Section 2(b)(1)-(2) are not Copyright and Similar\n"
  "     Rights.\n"
  "\n"
  "  d. Effective Technological Measures means those measures that, in the\n"
  "     absence of proper authority, may not be circumvented under laws\n"
  "     fulfilling obligations under Article 11 of the WIPO Copyright\n"
  "     Treaty adopted on December 20, 1996, and/or similar international\n"
  "     agreements.\n"
  "\n"
  "  e. Exceptions and Limitations means fair use, fair dealing, and/or\n"
  "     any other exception or limitation to Copyright and Similar Rights\n"
  "     that applies to Your use of the Licensed Material.\n"
  "\n"
  "  f. Licensed Material means the artistic or literary work, database,\n"
  "     or other material to which the Licensor applied this Public\n"
  "     License.\n"
  "\n"
  "  g. Licensed Rights means the rights granted to You subject to the\n"
  "     terms and conditions of this Public License, which are limited to\n"
  "     all Copyright and Similar Rights that apply to Your use of the\n"
  "     Licensed Material and that the Licensor has authority to license.\n"
  "\n"
  "  h. Licensor means the individual(s) or entity(ies) granting rights\n"
  "     under this Public License.\n"
  "\n"
  "  i. Share means to provide material to the public by any means or\n"
  "     process that requires permission under the Licensed Rights, such\n"
  "     as reproduction, public display, public performance, distribution,\n"
  "     dissemination, communication, or importation, and to make material\n"
  "     available to the public including in ways that members of the\n"
  "     public may access the material from a place and at a time\n"
  "     individually chosen by them.\n"
  "\n"
  "  j. Sui Generis Database Rights means rights other than copyright\n"
  "     resulting from Directive 96/9/EC of the European Parliament and of\n"
  "     the Council of 11 March 1996 on the legal protection of databases,\n"
  "     as amended and/or succeeded, as well as other essentially\n"
  "     equivalent rights anywhere in the world.\n"
  "\n"
  "  k. You means the individual or entity exercising the Licensed Rights\n"
  "     under this Public License. Your has a corresponding meaning.\n"
  "\n"
  "\n"
  "Section 2 -- Scope.\n"
  "\n"
  "  a. License grant.\n"
  "\n"
  "       1. Subject to the terms and conditions of this Public License,\n"
  "          the Licensor hereby grants You a worldwide, royalty-free,\n"
  "          non-sublicensable, non-exclusive, irrevocable license to\n"
  "          exercise the Licensed Rights in the Licensed Material to:\n"
  "\n"
  "            a. reproduce and Share the Licensed Material, in whole or\n"
  "               in part; and\n"
  "\n"
  "            b. produce, reproduce, and Share Adapted Material.\n"
  "\n"
  "       2. Exceptions and Limitations. For the avoidance of doubt, where\n"
  "          Exceptions and Limitations apply to Your use, this Public\n"
  "          License does not apply, and You do not need to comply with\n"
  "          its terms and conditions.\n"
  "\n"
  "       3. Term. The term of this Public License is specified in Section\n"
  "          6(a).\n"
  "\n"
  "       4. Media and formats; technical modifications allowed. The\n"
  "          Licensor authorizes You to exercise the Licensed Rights in\n"
  "          all media and formats whether now known or hereafter created,\n"
  "          and to make technical modifications necessary to do so. The\n"
  "          Licensor waives and/or agrees not to assert any right or\n"
  "          authority to forbid You from making technical modifications\n"
  "          necessary to exercise the Licensed Rights, including\n"
  "          technical modifications necessary to circumvent Effective\n"
  "          Technological Measures. For purposes of this Public License,\n"
  "          simply making modifications authorized by this Section 2(a)\n"
  "          (4) never produces Adapted Material.\n"
  "\n"
  "       5. Downstream recipients.\n"
  "\n"
  "            a. Offer from the Licensor -- Licensed Material. Every\n"
  "               recipient of the Licensed Material automatically\n"
  "               receives an offer from the Licensor to exercise the\n"
  "               Licensed Rights under the terms and conditions of this\n"
  "               Public License.\n"
  "\n"
  "            b. No downstream restrictions. You may not offer or impose\n"
  "               any additional or different terms or conditions on, or\n"
  "               apply any Effective Technological Measures to, the\n"
  "               Licensed Material if doing so restricts exercise of the\n"
  "               Licensed Rights by any recipient of the Licensed\n"
  "               Material.\n"
  "\n"
  "       6. No endorsement. Nothing in this Public License constitutes or\n"
  "          may be construed as permission to assert or imply that You\n"
  "          are, or that Your use of the Licensed Material is, connected\n"
  "          with, or sponsored, endorsed, or granted official status by,\n"
  "          the Licensor or others designated to receive attribution as\n"
  "          provided in Section 3(a)(1)(A)(i).\n"
  "\n"
  "  b. Other rights.\n"
  "\n"
  "       1. Moral rights, such as the right of integrity, are not\n"
  "          licensed under this Public License, nor are publicity,\n"
  "          privacy, and/or other similar personality rights; however, to\n"
  "          the extent possible, the Licensor waives and/or agrees not to\n"
  "          assert any such rights held by the Licensor to the limited\n"
  "          extent necessary to allow You to exercise the Licensed\n"
  "          Rights, but not otherwise.\n"
  "\n"
  "       2. Patent and trademark rights are not licensed under this\n"
  "          Public License.\n"
  "\n"
  "       3. To the extent possible, the Licensor waives any right to\n"
  "          collect royalties from You for the exercise of the Licensed\n"
  "          Rights, whether directly or through a collecting society\n"
  "          under any voluntary or waivable statutory or compulsory\n"
  "          licensing scheme. In all other cases the Licensor expressly\n"
  "          reserves any right to collect such royalties.\n"
  "\n"
  "\n"
  "Section 3 -- License Conditions.\n"
  "\n"
  "Your exercise of the Licensed Rights is expressly made subject to the\n"
  "following conditions.\n"
  "\n"
  "  a. Attribution.\n"
  "\n"
  "       1. If You Share the Licensed Material (including in modified\n"
  "          form), You must:\n"
  "\n"
  "            a. retain the following if it is supplied by the Licensor\n"
  "               with the Licensed Material:\n"
  "\n"
  "                 i. identification of the creator(s) of the Licensed\n"
  "                    Material and any others designated to receive\n"
  "                    attribution, in any reasonable manner requested by\n"
  "                    the Licensor (including by pseudonym if\n"
  "                    designated);\n"
  "\n"
  "                ii. a copyright notice;\n"
  "\n"
  "               iii. a notice that refers to this Public License;\n"
  "\n"
  "                iv. a notice that refers to the disclaimer of\n"
  "                    warranties;\n"
  "\n"
  "                 v. a URI or hyperlink to the Licensed Material to the\n"
  "                    extent reasonably practicable;\n"
  "\n"
  "            b. indicate if You modified the Licensed Material and\n"
  "               retain an indication of any previous modifications; and\n"
  "\n"
  "            c. indicate the Licensed Material is licensed under this\n"
  "               Public License, and include the text of, or the URI or\n"
  "               hyperlink to, this Public License.\n"
  "\n"
  "       2. You may satisfy the conditions in Section 3(a)(1) in any\n"
  "          reasonable manner based on the medium, means, and context in\n"
  "          which You Share the Licensed Material. For example, it may be\n"
  "          reasonable to satisfy the conditions by providing a URI or\n"
  "          hyperlink to a resource that includes the required\n"
  "          information.\n"
  "\n"
  "       3. If requested by the Licensor, You must remove any of the\n"
  "          information required by Section 3(a)(1)(A) to the extent\n"
  "          reasonably practicable.\n"
  "\n"
  "       4. If You Share Adapted Material You produce, the Adapter's\n"
  "          License You apply must not prevent recipients of the Adapted\n"
  "          Material from complying with this Public License.\n"
  "\n"
  "\n"
  "Section 4 -- Sui Generis Database Rights.\n"
  "\n"
  "Where the Licensed Rights include Sui Generis Database Rights that\n"
  "apply to Your use of the Licensed Material:\n"
  "\n"
  "  a. for the avoidance of doubt, Section 2(a)(1) grants You the right\n"
  "     to extract, reuse, reproduce, and Share all or a substantial\n"
  "     portion of the contents of the database;\n"
  "\n"
  "  b. if You include all or a substantial portion of the database\n"
  "     contents in a database in which You have Sui Generis Database\n"
  "     Rights, then the database in which You have Sui Generis Database\n"
  "     Rights (but not its individual contents) is Adapted Material; and\n"
  "\n"
  "  c. You must comply with the conditions in Section 3(a) if You Share\n"
  "     all or a substantial portion of the contents of the database.\n"
  "\n"
  "For the avoidance of doubt, this Section 4 supplements and does not\n"
  "replace Your obligations under this Public License where the Licensed\n"
  "Rights include other Copyright and Similar Rights.\n"
  "\n"
  "\n"
  "Section 5 -- Disclaimer of Warranties and Limitation of Liability.\n"
  "\n"
  "  a. UNLESS OTHERWISE SEPARATELY UNDERTAKEN BY THE LICENSOR, TO THE\n"
  "     EXTENT POSSIBLE, THE LICENSOR OFFERS THE LICENSED MATERIAL AS-IS\n"
  "     AND AS-AVAILABLE, AND MAKES NO REPRESENTATIONS OR WARRANTIES OF\n"
  "     ANY KIND CONCERNING THE LICENSED MATERIAL, WHETHER EXPRESS,\n"
  "     IMPLIED, STATUTORY, OR OTHER. THIS INCLUDES, WITHOUT LIMITATION,\n"
  "     WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR\n"
  "     PURPOSE, NON-INFRINGEMENT, ABSENCE OF LATENT OR OTHER DEFECTS,\n"
  "     ACCURACY, OR THE PRESENCE OR ABSENCE OF ERRORS, WHETHER OR NOT\n"
  "     KNOWN OR DISCOVERABLE. WHERE DISCLAIMERS OF WARRANTIES ARE NOT\n"
  "     ALLOWED IN FULL OR IN PART, THIS DISCLAIMER MAY NOT APPLY TO YOU.\n"
  "\n"
  "  b. TO THE EXTENT POSSIBLE, IN NO EVENT WILL THE LICENSOR BE LIABLE\n"
  "     TO YOU ON ANY LEGAL THEORY (INCLUDING, WITHOUT LIMITATION,\n"
  "     NEGLIGENCE) OR OTHERWISE FOR ANY DIRECT, SPECIAL, INDIRECT,\n"
  "     INCIDENTAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR OTHER LOSSES,\n"
  "     COSTS, EXPENSES, OR DAMAGES ARISING OUT OF THIS PUBLIC LICENSE OR\n"
  "     USE OF THE LICENSED MATERIAL, EVEN IF THE LICENSOR HAS BEEN\n"
  "     ADVISED OF THE POSSIBILITY OF SUCH LOSSES, COSTS, EXPENSES, OR\n"
  "     DAMAGES. WHERE A LIMITATION OF LIABILITY IS NOT ALLOWED IN FULL OR\n"
  "     IN PART, THIS LIMITATION MAY NOT APPLY TO YOU.\n"
  "\n"
  "  c. The disclaimer of warranties and limitation of liability provided\n"
  "     above shall be interpreted in a manner that, to the extent\n"
  "     possible, most closely approximates an absolute disclaimer and\n"
  "     waiver of all liability.\n"
  "\n"
  "\n"
  "Section 6 -- Term and Termination.\n"
  "\n"
  "  a. This Public License applies for the term of the Copyright and\n"
  "     Similar Rights licensed here. However, if You fail to comply with\n"
  "     this Public License, then Your rights under this Public License\n"
  "     terminate automatically.\n"
  "\n"
  "  b. Where Your right to use the Licensed Material has terminated under\n"
  "     Section 6(a), it reinstates:\n"
  "\n"
  "       1. automatically as of the date the violation is cured, provided\n"
  "          it is cured within 30 days of Your discovery of the\n"
  "          violation; or\n"
  "\n"
  "       2. upon express reinstatement by the Licensor.\n"
  "\n"
  "     For the avoidance of doubt, this Section 6(b) does not affect any\n"
  "     right the Licensor may have to seek remedies for Your violations\n"
  "     of this Public License.\n"
  "\n"
  "  c. For the avoidance of doubt, the Licensor may also offer the\n"
  "     Licensed Material under separate terms or conditions or stop\n"
  "     distributing the Licensed Material at any time; however, doing so\n"
  "     will not terminate this Public License.\n"
  "\n"
  "  d. Sections 1, 5, 6, 7, and 8 survive termination of this Public\n"
  "     License.\n"
  "\n"
  "\n"
  "Section 7 -- Other Terms and Conditions.\n"
  "\n"
  "  a. The Licensor shall not be bound by any additional or different\n"
  "     terms or conditions communicated by You unless expressly agreed.\n"
  "\n"
  "  b. Any arrangements, understandings, or agreements regarding the\n"
  "     Licensed Material not stated herein are separate from and\n"
  "     independent of the terms and conditions of this Public License.\n"
  "\n"
  "\n"
  "Section 8 -- Interpretation.\n"
  "\n"
  "  a. For the avoidance of doubt, this Public License does not, and\n"
  "     shall not be interpreted to, reduce, limit, restrict, or impose\n"
  "     conditions on any use of the Licensed Material that could lawfully\n"
  "     be made without permission under this Public License.\n"
  "\n"
  "  b. To the extent possible, if any provision of this Public License is\n"
  "     deemed unenforceable, it shall be automatically reformed to the\n"
  "     minimum extent necessary to make it enforceable. If the provision\n"
  "     cannot be reformed, it shall be severed from this Public License\n"
  "     without affecting the enforceability of the remaining terms and\n"
  "     conditions.\n"
  "\n"
  "  c. No term or condition of this Public License will be waived and no\n"
  "     failure to comply consented to unless expressly agreed to by the\n"
  "     Licensor.\n"
  "\n"
  "  d. Nothing in this Public License constitutes or may be interpreted\n"
  "     as a limitation upon, or waiver of, any privileges and immunities\n"
  "     that apply to the Licensor or You, including from the legal\n"
  "     processes of any jurisdiction or authority.\n"
  "\n"
  "\n"
  "=======================================================================\n"
  "\n"
  "Creative Commons is not a party to its public\n"
  "licenses. Notwithstanding, Creative Commons may elect to apply one of\n"
  "its public licenses to material it publishes and in those instances\n"
  "will be considered the “Licensor.” The text of the Creative Commons\n"
  "public licenses is dedicated to the public domain under the CC0 Public\n"
  "Domain Dedication. Except for the limited purpose of indicating that\n"
  "material is shared under a Creative Commons public license or as\n"
  "otherwise permitted by the Creative Commons policies published at\n"
  "creativecommons.org/policies, Creative Commons does not authorize the\n"
  "use of the trademark \"Creative Commons\" or any other trademark or logo\n"
  "of Creative Commons without its prior written consent including,\n"
  "without limitation, in connection with any unauthorized modifications\n"
  "to any of its public licenses or any other arrangements,\n"
  "understandings, or agreements concerning use of licensed material. For\n"
  "the avoidance of doubt, this paragraph does not form part of the\n"
  "public licenses.\n"
  "\n"
  "Creative Commons may be contacted at creativecommons.org.\n",

  // LICENSE: GPLv2
  "                    GNU GENERAL PUBLIC LICENSE\n"
  "                       Version 2, June 1991\n"
  "\n"
  " Copyright (C) 1989, 1991 Free Software Foundation, Inc.,\n"
  " 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"
  " Everyone is permitted to copy and distribute verbatim copies\n"
  " of this license document, but changing it is not allowed.\n"
  "\n"
  "                            Preamble\n"
  "\n"
  "  The licenses for most software are designed to take away your\n"
  "freedom to share and change it.  By contrast, the GNU General Public\n"
  "License is intended to guarantee your freedom to share and change free\n"
  "software--to make sure the software is free for all its users.  This\n"
  "General Public License applies to most of the Free Software\n"
  "Foundation's software and to any other program whose authors commit to\n"
  "using it.  (Some other Free Software Foundation software is covered by\n"
  "the GNU Lesser General Public License instead.)  You can apply it to\n"
  "your programs, too.\n"
  "\n"
  "  When we speak of free software, we are referring to freedom, not\n"
  "price.  Our General Public Licenses are designed to make sure that you\n"
  "have the freedom to distribute copies of free software (and charge for\n"
  "this service if you wish), that you receive source code or can get it\n"
  "if you want it, that you can change the software or use pieces of it\n"
  "in new free programs; and that you know you can do these things.\n"
  "\n"
  "  To protect your rights, we need to make restrictions that forbid\n"
  "anyone to deny you these rights or to ask you to surrender the rights.\n"
  "These restrictions translate to certain responsibilities for you if you\n"
  "distribute copies of the software, or if you modify it.\n"
  "\n"
  "  For example, if you distribute copies of such a program, whether\n"
  "gratis or for a fee, you must give the recipients all the rights that\n"
  "you have.  You must make sure that they, too, receive or can get the\n"
  "source code.  And you must show them these terms so they know their\n"
  "rights.\n"
  "\n"
  "  We protect your rights with two steps: (1) copyright the software, and\n"
  "(2) offer you this license which gives you legal permission to copy,\n"
  "distribute and/or modify the software.\n"
  "\n"
  "  Also, for each author's protection and ours, we want to make certain\n"
  "that everyone understands that there is no warranty for this free\n"
  "software.  If the software is modified by someone else and passed on, we\n"
  "want its recipients to know that what they have is not the original, so\n"
  "that any problems introduced by others will not reflect on the original\n"
  "authors' reputations.\n"
  "\n"
  "  Finally, any free program is threatened constantly by software\n"
  "patents.  We wish to avoid the danger that redistributors of a free\n"
  "program will individually obtain patent licenses, in effect making the\n"
  "program proprietary.  To prevent this, we have made it clear that any\n"
  "patent must be licensed for everyone's free use or not licensed at all.\n"
  "\n"
  "  The precise terms and conditions for copying, distribution and\n"
  "modification follow.\n"
  "\n"
  "                    GNU GENERAL PUBLIC LICENSE\n"
  "   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n"
  "\n"
  "  0. This License applies to any program or other work which contains\n"
  "a notice placed by the copyright holder saying it may be distributed\n"
  "under the terms of this General Public License.  The \"Program\", below,\n"
  "refers to any such program or work, and a \"work based on the Program\"\n"
  "means either the Program or any derivative work under copyright law:\n"
  "that is to say, a work containing the Program or a portion of it,\n"
  "either verbatim or with modifications and/or translated into another\n"
  "language.  (Hereinafter, translation is included without limitation in\n"
  "the term \"modification\".)  Each licensee is addressed as \"you\".\n"
  "\n"
  "Activities other than copying, distribution and modification are not\n"
  "covered by this License; they are outside its scope.  The act of\n"
  "running the Program is not restricted, and the output from the Program\n"
  "is covered only if its contents constitute a work based on the\n"
  "Program (independent of having been made by running the Program).\n"
  "Whether that is true depends on what the Program does.\n"
  "\n"
  "  1. You may copy and distribute verbatim copies of the Program's\n"
  "source code as you receive it, in any medium, provided that you\n"
  "conspicuously and appropriately publish on each copy an appropriate\n"
  "copyright notice and disclaimer of warranty; keep intact all the\n"
  "notices that refer to this License and to the absence of any warranty;\n"
  "and give any other recipients of the Program a copy of this License\n"
  "along with the Program.\n"
  "\n"
  "You may charge a fee for the physical act of transferring a copy, and\n"
  "you may at your option offer warranty protection in exchange for a fee.\n"
  "\n"
  "  2. You may modify your copy or copies of the Program or any portion\n"
  "of it, thus forming a work based on the Program, and copy and\n"
  "distribute such modifications or work under the terms of Section 1\n"
  "above, provided that you also meet all of these conditions:\n"
  "\n"
  "    a) You must cause the modified files to carry prominent notices\n"
  "    stating that you changed the files and the date of any change.\n"
  "\n"
  "    b) You must cause any work that you distribute or publish, that in\n"
  "    whole or in part contains or is derived from the Program or any\n"
  "    part thereof, to be licensed as a whole at no charge to all third\n"
  "    parties under the terms of this License.\n"
  "\n"
  "    c) If the modified program normally reads commands interactively\n"
  "    when run, you must cause it, when started running for such\n"
  "    interactive use in the most ordinary way, to print or display an\n"
  "    announcement including an appropriate copyright notice and a\n"
  "    notice that there is no warranty (or else, saying that you provide\n"
  "    a warranty) and that users may redistribute the program under\n"
  "    these conditions, and telling the user how to view a copy of this\n"
  "    License.  (Exception: if the Program itself is interactive but\n"
  "    does not normally print such an announcement, your work based on\n"
  "    the Program is not required to print an announcement.)\n"
  "\n"
  "These requirements apply to the modified work as a whole.  If\n"
  "identifiable sections of that work are not derived from the Program,\n"
  "and can be reasonably considered independent and separate works in\n"
  "themselves, then this License, and its terms, do not apply to those\n"
  "sections when you distribute them as separate works.  But when you\n"
  "distribute the same sections as part of a whole which is a work based\n"
  "on the Program, the distribution of the whole must be on the terms of\n"
  "this License, whose permissions for other licensees extend to the\n"
  "entire whole, and thus to each and every part regardless of who wrote it.\n"
  "\n"
  "Thus, it is not the intent of this section to claim rights or contest\n"
  "your rights to work written entirely by you; rather, the intent is to\n"
  "exercise the right to control the distribution of derivative or\n"
  "collective works based on the Program.\n"
  "\n"
  "In addition, mere aggregation of another work not based on the Program\n"
  "with the Program (or with a work based on the Program) on a volume of\n"
  "a storage or distribution medium does not bring the other work under\n"
  "the scope of this License.\n"
  "\n"
  "  3. You may copy and distribute the Program (or a work based on it,\n"
  "under Section 2) in object code or executable form under the terms of\n"
  "Sections 1 and 2 above provided that you also do one of the following:\n"
  "\n"
  "    a) Accompany it with the complete corresponding machine-readable\n"
  "    source code, which must be distributed under the terms of Sections\n"
  "    1 and 2 above on a medium customarily used for software interchange; or,\n"
  "\n"
  "    b) Accompany it with a written offer, valid for at least three\n"
  "    years, to give any third party, for a charge no more than your\n"
  "    cost of physically performing source distribution, a complete\n"
  "    machine-readable copy of the corresponding source code, to be\n"
  "    distributed under the terms of Sections 1 and 2 above on a medium\n"
  "    customarily used for software interchange; or,\n"
  "\n"
  "    c) Accompany it with the information you received as to the offer\n"
  "    to distribute corresponding source code.  (This alternative is\n"
  "    allowed only for noncommercial distribution and only if you\n"
  "    received the program in object code or executable form with such\n"
  "    an offer, in accord with Subsection b above.)\n"
  "\n"
  "The source code for a work means the preferred form of the work for\n"
  "making modifications to it.  For an executable work, complete source\n"
  "code means all the source code for all modules it contains, plus any\n"
  "associated interface definition files, plus the scripts used to\n"
  "control compilation and installation of the executable.  However, as a\n"
  "special exception, the source code distributed need not include\n"
  "anything that is normally distributed (in either source or binary\n"
  "form) with the major components (compiler, kernel, and so on) of the\n"
  "operating system on which the executable runs, unless that component\n"
  "itself accompanies the executable.\n"
  "\n"
  "If distribution of executable or object code is made by offering\n"
  "access to copy from a designated place, then offering equivalent\n"
  "access to copy the source code from the same place counts as\n"
  "distribution of the source code, even though third parties are not\n"
  "compelled to copy the source along with the object code.\n"
  "\n"
  "  4. You may not copy, modify, sublicense, or distribute the Program\n"
  "except as expressly provided under this License.  Any attempt\n"
  "otherwise to copy, modify, sublicense or distribute the Program is\n"
  "void, and will automatically terminate your rights under this License.\n"
  "However, parties who have received copies, or rights, from you under\n"
  "this License will not have their licenses terminated so long as such\n"
  "parties remain in full compliance.\n"
  "\n"
  "  5. You are not required to accept this License, since you have not\n"
  "signed it.  However, nothing else grants you permission to modify or\n"
  "distribute the Program or its derivative works.  These actions are\n"
  "prohibited by law if you do not accept this License.  Therefore, by\n"
  "modifying or distributing the Program (or any work based on the\n"
  "Program), you indicate your acceptance of this License to do so, and\n"
  "all its terms and conditions for copying, distributing or modifying\n"
  "the Program or works based on it.\n"
  "\n"
  "  6. Each time you redistribute the Program (or any work based on the\n"
  "Program), the recipient automatically receives a license from the\n"
  "original licensor to copy, distribute or modify the Program subject to\n"
  "these terms and conditions.  You may not impose any further\n"
  "restrictions on the recipients' exercise of the rights granted herein.\n"
  "You are not responsible for enforcing compliance by third parties to\n"
  "this License.\n"
  "\n"
  "  7. If, as a consequence of a court judgment or allegation of patent\n"
  "infringement or for any other reason (not limited to patent issues),\n"
  "conditions are imposed on you (whether by court order, agreement or\n"
  "otherwise) that contradict the conditions of this License, they do not\n"
  "excuse you from the conditions of this License.  If you cannot\n"
  "distribute so as to satisfy simultaneously your obligations under this\n"
  "License and any other pertinent obligations, then as a consequence you\n"
  "may not distribute the Program at all.  For example, if a patent\n"
  "license would not permit royalty-free redistribution of the Program by\n"
  "all those who receive copies directly or indirectly through you, then\n"
  "the only way you could satisfy both it and this License would be to\n"
  "refrain entirely from distribution of the Program.\n"
  "\n"
  "If any portion of this section is held invalid or unenforceable under\n"
  "any particular circumstance, the balance of the section is intended to\n"
  "apply and the section as a whole is intended to apply in other\n"
  "circumstances.\n"
  "\n"
  "It is not the purpose of this section to induce you to infringe any\n"
  "patents or other property right claims or to contest validity of any\n"
  "such claims; this section has the sole purpose of protecting the\n"
  "integrity of the free software distribution system, which is\n"
  "implemented by public license practices.  Many people have made\n"
  "generous contributions to the wide range of software distributed\n"
  "through that system in reliance on consistent application of that\n"
  "system; it is up to the author/donor to decide if he or she is willing\n"
  "to distribute software through any other system and a licensee cannot\n"
  "impose that choice.\n"
  "\n"
  "This section is intended to make thoroughly clear what is believed to\n"
  "be a consequence of the rest of this License.\n"
  "\n"
  "  8. If the distribution and/or use of the Program is restricted in\n"
  "certain countries either by patents or by copyrighted interfaces, the\n"
  "original copyright holder who places the Program under this License\n"
  "may add an explicit geographical distribution limitation excluding\n"
  "those countries, so that distribution is permitted only in or among\n"
  "countries not thus excluded.  In such case, this License incorporates\n"
  "the limitation as if written in the body of this License.\n"
  "\n"
  "  9. The Free Software Foundation may publish revised and/or new versions\n"
  "of the General Public License from time to time.  Such new versions will\n"
  "be similar in spirit to the present version, but may differ in detail to\n"
  "address new problems or concerns.\n"
  "\n"
  "Each version is given a distinguishing version number.  If the Program\n"
  "specifies a version number of this License which applies to it and \"any\n"
  "later version\", you have the option of following the terms and conditions\n"
  "either of that version or of any later version published by the Free\n"
  "Software Foundation.  If the Program does not specify a version number of\n"
  "this License, you may choose any version ever published by the Free Software\n"
  "Foundation.\n"
  "\n"
  "  10. If you wish to incorporate parts of the Program into other free\n"
  "programs whose distribution conditions are different, write to the author\n"
  "to ask for permission.  For software which is copyrighted by the Free\n"
  "Software Foundation, write to the Free Software Foundation; we sometimes\n"
  "make exceptions for this.  Our decision will be guided by the two goals\n"
  "of preserving the free status of all derivatives of our free software and\n"
  "of promoting the sharing and reuse of software generally.\n"
  "\n"
  "                            NO WARRANTY\n"
  "\n"
  "  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY\n"
  "FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN\n"
  "OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES\n"
  "PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED\n"
  "OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\n"
  "MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS\n"
  "TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE\n"
  "PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,\n"
  "REPAIR OR CORRECTION.\n"
  "\n"
  "  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING\n"
  "WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR\n"
  "REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,\n"
  "INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING\n"
  "OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED\n"
  "TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY\n"
  "YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER\n"
  "PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE\n"
  "POSSIBILITY OF SUCH DAMAGES.\n"
  "\n"
  "                     END OF TERMS AND CONDITIONS\n"
  "\n"
  "            How to Apply These Terms to Your New Programs\n"
  "\n"
  "  If you develop a new program, and you want it to be of the greatest\n"
  "possible use to the public, the best way to achieve this is to make it\n"
  "free software which everyone can redistribute and change under these terms.\n"
  "\n"
  "  To do so, attach the following notices to the program.  It is safest\n"
  "to attach them to the start of each source file to most effectively\n"
  "convey the exclusion of warranty; and each file should have at least\n"
  "the \"copyright\" line and a pointer to where the full notice is found.\n"
  "\n"
  "    <one line to give the program's name and a brief idea of what it does.>\n"
  "    Copyright (C) <year>  <name of author>\n"
  "\n"
  "    This program is free software; you can redistribute it and/or modify\n"
  "    it under the terms of the GNU General Public License as published by\n"
  "    the Free Software Foundation; either version 2 of the License, or\n"
  "    (at your option) any later version.\n"
  "\n"
  "    This program is distributed in the hope that it will be useful,\n"
  "    but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
  "    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
  "    GNU General Public License for more details.\n"
  "\n"
  "    You should have received a copy of the GNU General Public License along\n"
  "    with this program; if not, write to the Free Software Foundation, Inc.,\n"
  "    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.\n"
  "\n"
  "Also add information on how to contact you by electronic and paper mail.\n"
  "\n"
  "If the program is interactive, make it output a short notice like this\n"
  "when it starts in an interactive mode:\n"
  "\n"
  "    Gnomovision version 69, Copyright (C) year name of author\n"
  "    Gnomovision comes with ABSOLUTELY NO WARRANTY; for details type `show w'.\n"
  "    This is free software, and you are welcome to redistribute it\n"
  "    under certain conditions; type `show c' for details.\n"
  "\n"
  "The hypothetical commands `show w' and `show c' should show the appropriate\n"
  "parts of the General Public License.  Of course, the commands you use may\n"
  "be called something other than `show w' and `show c'; they could even be\n"
  "mouse-clicks or menu items--whatever suits your program.\n"
  "\n"
  "You should also get your employer (if you work as a programmer) or your\n"
  "school, if any, to sign a \"copyright disclaimer\" for the program, if\n"
  "necessary.  Here is a sample; alter the names:\n"
  "\n"
  "  Yoyodyne, Inc., hereby disclaims all copyright interest in the program\n"
  "  `Gnomovision' (which makes passes at compilers) written by James Hacker.\n"
  "\n"
  "  <signature of Ty Coon>, 1 April 1989\n"
  "  Ty Coon, President of Vice\n"
  "\n"
  "This General Public License does not permit incorporating your program into\n"
  "proprietary programs.  If your program is a subroutine library, you may\n"
  "consider it more useful to permit linking proprietary applications with the\n"
  "library.  If this is what you want to do, use the GNU Lesser General\n"
  "Public License instead of this License.\n",

  // LICENSE: MIT
  "Copyright (c) <year> <copyright holders>\n"
  "\n"
  "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
  "of this software and associated documentation files (the \"Software\"), to deal\n"
  "in the Software without restriction, including without limitation the rights\n"
  "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
  "copies of the Software, and to permit persons to whom the Software is\n"
  "furnished to do so, subject to the following conditions:\n"
  "\n"
  "The above copyright notice and this permission notice shall be included in all\n"
  "copies or substantial portions of the Software.\n"
  "\n"
  "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
  "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
  "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
  "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
  "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
  "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
  "SOFTWARE.\n",

  // LICENSE: Unlicense
  "This is free and unencumbered software released into the public domain.\n"
  "\n"
  "Anyone is free to copy, modify, publish, use, compile, sell, or\n"
  "distribute this software, either in source code form or as a compiled\n"
  "binary, for any purpose, commercial or non-commercial, and by any\n"
  "means.\n"
  "\n"
  "In jurisdictions that recognize copyright laws, the author or authors\n"
  "of this software dedicate any and all copyright interest in the\n"
  "software to the public domain. We make this dedication for the benefit\n"
  "of the public at large and to the detriment of our heirs and\n"
  "successors. We intend this dedication to be an overt act of\n"
  "relinquishment in perpetuity of all present and future rights to this\n"
  "software under copyright law.\n"
  "\n"
  "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n"
  "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n"
  "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n"
  "IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR\n"
  "OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,\n"
  "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR\n"
  "OTHER DEALINGS IN THE SOFTWARE.\n"
  "\n"
  "For more information, please refer to <http://unlicense.org/>\n",

};